CREATE TABLE meal
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name     VARCHAR(255)                            NOT NULL,
    calories INTEGER                                 NOT NULL,
    carbs    INTEGER                                 NOT NULL,
    protein  INTEGER                                 NOT NULL,
    fats     INTEGER                                 NOT NULL,
    fibers   INTEGER                                 NOT NULL,
    CONSTRAINT pk_meal PRIMARY KEY (id)
);